### ISSUE TITLE
code mod for breaking syntax changes

### ISSUE THREAD

**Issue by TkDodo** [tannerlinsley/react-query#2983]
<details>
  <summary>useQuery, useInfiniteQuery, queryClient.fetchQuery, queryClient.prefetchQuery, queryClient.fetchInfiniteQuery, queryClient.prefetchInfiniteQuery, useInfiniteQuery</summary>

```
input:
  useQuery('todos', fetchTodos)
output:
  useQuery(['todos'], fetchTodos)

input:
  useQuery(['todos'], fetchTodos, { staleTime: 1000 })
output:
  useQuery(['todos'], fetchTodos, { staleTime: 1000 })

input:
  useQuery(['todos'], { queryFn: fetchTodos, staleTime: 1000 })
output:
  useQuery(['todos'], { queryFn: fetchTodos, staleTime: 1000 })

input:
  useQuery('todos', { queryKey: ['notTodos'], queryFn: fetchTodos, staleTime: 1000 })
output:
  useQuery(['todos'], { queryKey: ['notTodos'], queryFn: fetchTodos, staleTime: 1000 })

input:
  useQuery({ queryKey: 'todos', staleTime: 1000 })
output:
  useQuery({ queryKey: ['todos'], staleTime: 1000 })
  
input:
  const key = 'todos'
  useQuery(key, { queryFn: fetchTodos, staleTime: 1000 })
output:
  useQuery({ queryKey: [key], queryFn: fetchTodos, staleTime: 1000 })

input:
  const queryKey = 'todos'
  useQuery({ queryKey, queryFn: fetchTodos, staleTime: 1000 })
output:
  useQuery({ queryKey: [queryKey], queryFn: fetchTodos, staleTime: 1000 })
  
input:
  const key = ['todos']
  useQuery(key, { queryFn: fetchTodos, staleTime: 1000 })
output:
  useQuery(key, { queryFn: fetchTodos, staleTime: 1000 })

input:
  const queryKey = ['todos']
  useQuery({ queryKey, queryFn: fetchTodos, staleTime: 1000 })
output:
  useQuery({ queryKey, queryFn: fetchTodos, staleTime: 1000 })

input:
  const queryKey = createKey()
  useQuery({ queryKey, queryFn: fetchTodos, staleTime: 1000 })
output:
  useQuery({ queryKey, queryFn: fetchTodos, staleTime: 1000 })

input:
  import { useQuery as useReactQuery } from 'react-query'
  const useQuery = (key, fn, options) => useReactQuery(key, fn, { ...options, staleTime: 1000 })
  useQuery('todos', fetchTodos, {})
output:
  import { useQuery as useReactQuery } from 'react-query'
  const useQuery = (key, fn, options) => useReactQuery(key, fn, { ...options, staleTime: 1000 })
  useQuery(['todos'], fetchTodos, {})

input:
  import * as RQ from 'react-query'
  const useQuery = (key, fn, options) => RQ.useQuery(key, fn, { ...options, staleTime: 1000 })
  useQuery('todos', fetchTodos, {})
output:
  import * as RQ from 'react-query'
  const useQuery = (key, fn, options) => RQ.useQuery(key, fn, { ...options, staleTime: 1000 })
  useQuery(['todos'], fetchTodos, {})
```
</details>

<details>
  <summary>
    queryClient.invalidateQueries, queryClient.refetchQueries, queryClient.resetQueries, queryClient.removeQueries, queryClient.cancelQueries
  </summary>

```
input:
  const queryClient = useQueryClient()
  queryClient.invalidateQueries('todos')
output:
  const queryClient = useQueryClient()
  queryClient.invalidateQueries(['todos'])

input:
  const queryClient = useQueryClient()
  queryClient.invalidateQueries('todos', { exact: true })
output:
  const queryClient = useQueryClient()
  queryClient.invalidateQueries(['todos'], { exact: true })

input:
  const queryClient = useQueryClient()
  queryClient.invalidateQueries(['todos'], { exact: true }, options)
output:
  const queryClient = useQueryClient()
  queryClient.invalidateQueries(['todos'], { exact: true }, options)

input:
  useQueryClient().invalidateQueries({ queryKey: 'todos', exact: true })
output:
  useQueryClient().invalidateQueries({ queryKey: ['todos'], exact: true })

input:
  useQueryClient().invalidateQueries({ queryKey: ['todos'], exact: true })
output:
  useQueryClient().invalidateQueries({ queryKey: ['todos'], exact: true })

input:
  const queryKey = 'todos'
  useQueryClient().invalidateQueries({ queryKey, exact: true })
output:
  useQueryClient().invalidateQueries({ queryKey: [queryKey], exact: true })

input:
  const queryKey = ['todos']
  useQueryClient().invalidateQueries({ queryKey, exact: true })
output:
  useQueryClient().invalidateQueries({ queryKey, exact: true })
```
</details>

<details>
  <summary>queryClient.getQueryData, queryClient.getQueryState, queryCache.find, queryClient.getQueriesData, queryClient.isFetching, useIsFetching, useIsMutating, queryCache.findAll, queryClient.setQueriesData</summary>

```
input:
  const queryClient = useQueryClient()
  queryClient.getQueryData('key', { exact: true })
output:
  const queryClient = useQueryClient()
  queryClient.getQueryData(['key'], { exact: true })

input:
  const queryClient = useQueryClient()
  queryClient.getQueryData(['key'], { exact: true })
output:
  const queryClient = useQueryClient()
  queryClient.getQueryData(['key'], { exact: true })
```
</details>

<details>
  <summary>queryClient.setQueryData, queryClient.setMutationDefaults, queryClient.getMutationDefaults, queryClient.setQueryDefaults, queryClient.getQueryDefaults</summary>

```diff
- fn(key, updater, options)
+ fn([key], updater, options)
```
</details>

<details>
  <summary>useMutation</summary>

same as `useQuery`, except that `queryKey` is `mutationKey`

</details>

<details>
  <summary>useQueries</summary>

An easy one because useQueries only gets an array passed, which should become an object. Nothing within query1 / query2 / query3 needs to change.

```diff
- useQueries([query1, query2, query3])
+ useQueries({ queries: [query1, query2, query3])
```

after that, inside the `queries` object, we need to change `queryKey` to be an array, like for `useQuery` with the object syntax.
</details>

**Comment by TkDodo** [comment]
@balazsmatepetro I've added some examples for `useQuery`. I will add more for the other methods a bit later. I hope I didn't make any syntax errors 😅

**Comment by balazsmatepetro** [comment]
Thank you much, it helps a lot! :)

**Comment by TkDodo** [comment]
@balazsmatepetro how are things on the code mod? Do you need any help?

**Comment by balazsmatepetro** [comment]
> @balazsmatepetro how are things on the code mod? Do you need any help?

Hi! I'm planning to open a PR at the end of this week. :)

**Comment by balazsmatepetro** [comment]
## Task list

Write codemods for:
- [x] `useQuery` hook
- [x] `useQueries` hook
- [x] `useInfiniteQuery` hook
- [ ] `useIsFetching` hook
- [ ] `useIsMutating` hook
- [x] `useMutation` hook
- [x] `QueryCache` methods
    - [ ] `find`
    - [ ] `findAll`
- [x] `QueryClient` methods
    - [x] Object syntax aware
        - [x] `cancelQueries`
        - [x] `fetchInfiniteQuery`
        - [x] `fetchQuery`
        - [x] `invalidateQueries`
        - [x] `prefetchInfiniteQuery`
        - [x] `prefetchQuery`
        - [x] `refetchQueries`
        - [x] `removeQueries`
        - [x] `resetQueries`
    - [x] Not object syntax aware
        - [x] `cancelQueries`
        - [x] `getMutationDefaults`
        - [x] `getQueriesData`
        - [x] `getQueryData`
        - [x] `getQueryDefaults`
        - [x] `getQueryState`
        - [x] `invalidateQueries`
        - [x] `isFetching`
        - [x] `refetchQueries`
        - [x] `removeQueries`
        - [x] `resetQueries`
        - [x] `setMutationDefaults`
        - [x] `setQueriesData`
        - [x] `setQueryData`
        - [x] `setQueryDefaults`

Additional tasks:
- [x] Add support for `mutationKey` in case of `useMutation` hook.
- [ ] Add support for template literals in case of query key.
- [ ] Try combine **ALL** codemods into a single one.
- [x] Move files under `v4` directory.
- [x] Reduce the number of repetitive test fixtures.
